FROM python:3.12-alpine
WORKDIR /app

COPY requirements.txt .
RUN apk add --no-cache ca-certificates
RUN pip install --upgrade pip && pip install -r requirements.txt

# copia tudo, incluindo o entrypoint.sh com CRLF
COPY . .

# remove o CR (\r) de cada linha e ajusta permissão
RUN sed -i 's/\r$//' entrypoint.sh \
 && chmod +x entrypoint.sh

EXPOSE 5000
ENTRYPOINT ["./entrypoint.sh"]
